### 서버 호출
GET http://localhost:3000

### location Test
POST http://capstoneserver-etkm.onrender.com/api/location
Content-Type: application/json

{
    "ssid": "Wifi",
    "mac": "testMac",
    "rssi": -1
}

### login Test
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "userId": "test@example.com",
    "password": "password123"
}

### register Test
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "userId": "test11@example.com",
    "password": "qwerty123",
    "name": "테스트",
    "year": "2000",
    "month": "3",
    "day": "12"
}