### 서버 호출
GET http://localhost:3000

### location Test
POST http://localhost:3000/api/location
Content-Type: application/json

{
    "ssid": "Wifi",
    "mac": "testMac",
    "rssi": -1
}

### login Test
POST https://capstoneserver-etkm.onrender.com/api/auth/login
Content-Type: application/json

{
    "userId": "testId",
    "password": "testPw"
}